
const PortfolioList = [
  {
    id:"1",
    title: "Jolie",
    subTitle: "Mockup Page for Jolie Fashion",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669648/jolie_bv8m1y.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498675859/jolie-iloveimg-compressed_wjcwwq.gif",
    descriptionTitle: "App Description",
    description1: "This wholesale clothing website has been built for a live client, Jolie. The purpose is three-fold:",
    description2: "New customers can register to become an authorized customer.",
    description3: "Authorized customers can view the brand's items and create sales orders.",
    description4: "The admin can authorize new customers, add/delete items, and view sales orders.",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML/CSS/Bootstrap to create layout that will be aestetically pleasing to both live client and his customers",
    tech2:"Handlebars to generate different layouts",
    tech3:"Node.js to control server.js APIs and routing",
    tech4:"Express.js as server framework",
    tech5:"Sequelize to set up database in node.js",
    tech6:"Passport.js to authenticate users",
    tech7:"Multer for uploading files",
    tech8:"Nodemailer to send emails",
    live: "https://jolie-wholesale.herokuapp.com/",
    github: "https://github.com/marcosl8686/FashionStore"

  },
  {
    id:"7",
    title: "Design-Test",
    subTitle: "Learning CSS tips",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669576/design_jyp385.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669859/design_krqrf5.gif",
    descriptionTitle: "Use of HTML & CSS tricks to build a stunning Web-page.",
    description1: "Created Page for a Fake Business OmniFood.",
    description2: "",
    description3: "",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML/CSS",
    tech2:"Javascript/jQuery",
    tech3:"",
    tech4:"",
    tech5:"",
    tech6:"",
    tech7:"",
    tech8:"",
    live: "https://marcosl8686.github.io/Design-Test/",
    github: "https://github.com/marcosl8686/Design-Test"
  },
  {
    id:"2",
    title: "Popcorn Now",
    subTitle: "Git WorkFlow",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669712/popcorn1_f9saz3.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498675536/PopcornNow-iloveimg-compressed_qdewjz.gif",
    descriptionTitle: "Movie Recommendation",
    description1: "Use of DataBase to store and retrieve user Inputs.",
    description2: "Use of API to build an web application.",
    description3: "",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML/CSS/Bootstrap",
    tech2:"JavaScript/jQuery",
    tech3:"API",
    tech4:"Lodash.js",
    tech5:"",
    tech6:"",
    tech7:"",
    tech8:"",
    live: "https://marcosl8686.github.io/PopCornNow/",
    github: "https://github.com/marcosl8686/PopCornNow"
  },
  {
    id:"3",
    title: "Video Search",
    subTitle: "Video App created using React, Redux & Youtube API",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669529/videoSearch_i1vqh0.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669567/videoSearch_ghrzg3.gif",
    descriptionTitle: "Search videos using Youtube API",
    description1: "Use of React and Redux to create simple video Application using Youtube API.",
    description2: "",
    description3: "",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML/CSS",
    tech2:"JavaScript",
    tech3:"API",
    tech4:"React.js",
    tech5:"Redux.js",
    tech6:"react-bootstrap",
    tech7:"",
    tech8:"",
    live: "https://marcosl8686.github.io/react-videoSearch/",
    github: "https://github.com/marcosl8686/react-videoSearch"
  },
  {
    id:"4",
    title: "Weather App",
    subTitle: "Weather App created using React, Redux & Weather API",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669518/weather_noscgl.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669563/weather_xkpsws.gif",
    descriptionTitle: "Search videos using Youtube API",
    description1: "Use of React and Redux to create simple video Application using Youtube API.",
    description2: "",
    description3: "",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML/CSS",
    tech2:"JavaScript",
    tech3:"API",
    tech4:"React.js",
    tech5:"Redux.js",
    tech6:"react-bootstrap",
    tech7:"",
    tech8:"",
    live: "https://github.com/marcosl8686/weather-app",
    github: "https://github.com/marcosl8686/weather-app"
  },
  {
    id:"5",
    title: "Goal Tracker",
    subTitle: "Intro to Handlebars and MVC architectural pattern",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669589/goaltracker_higtav.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669602/goaltracker_hcbmxt.gif",
    descriptionTitle: "KEEP TRACK OF YOUR GOALS",
    description1: "Use of Handlebars templating engine to dynamically create elements in HTML.",
    description2: "Follow MVC pattern.",
    description3: "Access MySQL database.",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML/CSS",
    tech2:"JavaScript/jQuery",
    tech3:"node.js",
    tech4:"handlebars",
    tech5:"Redux.js",
    tech6:"",
    tech7:"",
    tech8:"",
    live: "https://ml-goals.herokuapp.com/",
    github: "https://github.com/marcosl8686/GoalsTracker"
  },
  {
    id:"6",
    title: "Flashcards",
    subTitle: "Create an API that allows users to create two types of flashcards",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669531/flashcard_dmpavx.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669631/flashcards_bbtanm.gif",
    descriptionTitle: "CREATING APPLICATION WITH NODE.JS",
    description1: "Use of inquirer to store user data.",
    description2: "Modularize code with Node.js.",
    description3: "",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"node.js",
    tech2:"inquirer",
    tech3:"",
    tech4:"",
    tech5:"",
    tech6:"",
    tech7:"",
    tech8:"",
    live: "https://github.com/marcosl8686/Flashcard-Generator",
    github: "https://github.com/marcosl8686/Flashcard-Generator"
  },
  {
    id:"8",
    title: "Trivia",
    subTitle: "Dynamic functions With Jquery",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669746/trivia_e00mnf.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669775/Trivia_l6qjnd.gif",
    descriptionTitle: "ONE PUNCH MAN TRIVIA GAME",
    description1: "Dynamicallty Create elements in HTML with Jquery.",
    description2: "Use of Javascript Object notation.",
    description3: "Intro to DOM manipulation.",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML",
    tech2:"CSS",
    tech3:"Bootstrap",
    tech4:"Javascript",
    tech5:"jQuery",
    tech6:"",
    tech7:"",
    tech8:"",
    live: "https://marcosl8686.github.io/TriviaGame/",
    github: "https://github.com/marcosl8686/TriviaGame"
  },
  {
    id:"9",
    title: "RPG Game",
    subTitle: "Intro to Javascript & jQuery",
    img: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498669762/rpg_wqmryd.png",
    gif: "https://res.cloudinary.com/dskstxa5i/image/upload/v1498675865/RPG-iloveimg-compressed_bslqmy.gif",
    descriptionTitle: "RPG FIGHT INSPIRED BY FINAL FANTASY",
    description1: "Intro to Jquery.",
    description2: "Dynamically update HTML pages with the jQuery library.",
    description3: "Use of Javascript Timing Event.",
    description4: "",
    technologiesTitle: "TECHNOLOGIES USED",
    tech1:"HTML",
    tech2:"CSS",
    tech3:"Bootstrap",
    tech4:"Javascript",
    tech5:"jQuery",
    tech6:"",
    tech7:"",
    tech8:"",
    live: "https://marcosl8686.github.io/week-4-game/",
    github: "https://github.com/marcosl8686/week-4-game"
  }
]
export default PortfolioList
